#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc config border_width         3
bspc config window_gap          12
# Border
bspc config focused_border_color        "#0366D6"
bspc config normal_border_color         "#22292B"
bspc config active_border_color         "#22292B"

# preselect color
bspc config presel_feedback_color     "#7886df"

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true

# 特定程序窗口的设置
# 可以命令查看窗口的名称 xprop | grep WM_CLASS 后点击窗口即可
# 设置bspwm 的 rule
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a feh state=floating
bspc rule -a netease-cloud-music state=floating

# autostart shell
bash ~/.dotfile/script/feh.sh &
fcitx5 &
picom &
flameshot &
# 状态栏
bash ~/.config/polybar/launch.sh --material
